### ISSUE TITLE
bdist_rpm creates RPMs that depend wrongly on vsc-base instead of python-vsc-base.

### ISSUE THREAD

**Issue by piojo** [hpcugent/vsc-ldap#13] opened 2013-02-28 19:35 UTC
As you see:

``` bash
$ rpm -qp --requires $HOME/rpmbuild/RPMS/python-vsc-ldap-0.93-1.ug.noarch.rpm |grep vsc
vsc-base >= 0.90
```

And it won't install because:

``` bash
$ rpm -qp --provides $HOME/rpmbuild/RPMS/python-vsc-base-1.0-1.ug.noarch.rpm 
python-vsc-packages-common = 0.5
python-vsc-packages-logging = 0.14
python-vsc-packages-utils = 0.11
python-vsc-base = 1.0-1
python-vsc-base = 1.0-1.ug
```

**Comment by JensTimmerman** [comment] 2016-02-23 10:19
duplicate of https://github.com/hpcugent/vsc-ldap/issues/8

**Comment by itkovian** [comment] 2018-11-05 15:15
This is fixed.

**Closed by itkovian** 2018-11-05 15:15 UTC
